fcd: "/home/jiawei/data/terasim/test_cosmos/Mcity/raw_data/0_0/fcd_all.xml"  
net: "/home/jiawei/data/terasim/test_cosmos/Mcity/mcity.net.xml"        
output_dir: "/home/jiawei/data/terasim/test_cosmos/Mcity/pedestrian_crossing"  
  

start_time: 260         # Start time for visualization (default: 0)
end_time: 264        # End time for visualization (null = use all data)
ego_vehicle_id: "BV_9.3"
adv_vehicle_id: "BV_bike_flow_0.30"

animate: true        # true for animation, false for static plot
speed_colors: false   # Color trajectories by speed (overrides other colors)
lane_colors: false    # Color trajectories by lane (overrides vehicle type colors)

# Plot appearance
figsize: "9,12"       # Figure size in inches (width,height)
dpi: 300              # Resolution for saved images/animations

# Map styling
map_style:
  style: "EUR"                    # Map style: EUR, USA, etc.
  zoom_to_extents: false          # Auto-zoom to fit all roads (set false for custom view)
  show_title: false               # Show plot title
  show_labels: false              # Show axis labels
  plot_stop_lines: false           # Plot stop lines
  title: "Traffic Simulation"     # Custom title (if show_title: true)
  
  # Custom view settings (only used when zoom_to_extents: false)
  view:
    width: 60                    # View width in meters
    height: 80                   # View height in meters
    center_on_ego: true           # Center view on ego vehicle (if false, use fixed center)
    center_x: 0                   # Fixed center X coordinate (only if center_on_ego: false)
    center_y: 0                   # Fixed center Y coordinate (only if center_on_ego: false)
  
  # Colors for map elements
  colors:
    lane_color: '0.9'
    lane_marking_color: '0.2'

  tl_phases:
    green: ["466521849#1_1", "466521849#1_0"]
    red: []

# Vehicle type coloring (when speed_colors and lane_colors are false):
# - Regular vehicles (BV_*, AV): red
# - Bicycles: yellow  
# - Pedestrians (VRU_*): blue

# Animation settings (only used when animate: true)
# - Frame rate: 10 fps
# - Marker sizes: vehicles=6, bicycles=4, pedestrians=2
# - Uses ffmpeg writer for MP4 output